export const passwords = [
  {
    application: 'Amazon',
    username: 'amazon@user',
    passphrase: '@SenhaAmazon123',
    website: 'amazon.com',
    notes:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariat.',
    userId: 1,
    tags: ['E-commerce', 'compras'],
    favorite: false,
    inBin: false,
    createdAt: '2023-11-15T12:30:00Z'
  },
  {
    application: 'Google',
    username: 'google@user',
    passphrase: '@senhagoogle',
    website: 'google.com',
    notes: 'Some notes about Google.',
    userId: 1,
    tags: ['Search Engine', 'Technology'],
    favorite: false,
    inBin: false,
    createdAt: '2023-11-15T12:30:00Z'
  },
  {
    application: 'Twitter',
    username: 'twitter@user',
    passphrase: '@senhatwitter',
    website: 'twitter.com',
    notes: 'Some notes about Twitter.',
    userId: 1,
    tags: ['Social Networking', 'Microblogging'],
    favorite: true,
    inBin: false,
    createdAt: '2023-11-15T09:15:00Z'
  },
  {
    application: 'YouTube',
    username: 'youtube@user',
    passphrase: '@senhayoutube',
    website: 'youtube.com',
    notes: 'Some notes about YouTube.',
    userId: 1,
    tags: ['streaming'],
    favorite: true,
    inBin: false,
    createdAt: '2023-11-15T10:00:00Z'
  },
  {
    application: 'GitHub',
    username: 'github@user',
    passphrase: '@senhagithub',
    website: 'github.com.br',
    notes: 'Some notes about GitHub.',
    userId: 1,
    tags: ['Version Control', 'Collaboration'],
    favorite: true,
    inBin: false,
    createdAt: '2023-11-15T09:45:00Z'
  },
  {
    //id: '19',
    application: 'Instagram',
    username: 'instagram@user',
    passphrase: '@senhainstagram',
    website: 'instagram.com',
    notes: 'Some notes about Instagram.',
    userId: 1,
    tags: ['Photo Sharing', 'Social Networking'],
    favorite: true,
    inBin: false,
    createdAt: '2023-11-15T08:15:00Z'
  },
  {
    application: 'Spotify',
    username: 'spotify@user',
    passphrase: '@senhaspotify',
    website: 'spotify.com',
    notes: 'Some notes about Spotify.',
    userId: 1,
    tags: ['Streaming', 'Music'],
    favorite: false,
    inBin: false,
    createdAt: '2023-11-15T11:45:00Z'
  },
  {
    application: 'Reddit',
    username: 'reddit@user',
    passphrase: '@senhareddit',
    website: 'reddit.com',
    notes: 'Some notes about Reddit.',
    userId: 1,
    tags: ['Discussion', 'Community'],
    favorite: false,
    inBin: false,
    createdAt: '2023-11-15T11:00:00Z'
  },
  {
    //id: '22',
    application: 'LinkedIn',
    username: 'linkedin@user',
    passphrase: '@senhalinkedin',
    website: 'linkedin.com',
    notes: 'Some notes about LinkedIn.',
    userId: 1,
    tags: ['Networking', 'Career'],
    favorite: false,
    inBin: false,
    createdAt: '2023-11-15T15:15:00Z'
  },
  {
    application: 'Snapchat',
    username: 'snapchat@user',
    passphrase: '@senhasnapchat',
    website: 'snapchat.com',
    notes: 'Some notes about Snapchat.',
    userId: 1,
    tags: ['Photo Sharing', 'Messaging'],
    favorite: true,
    inBin: false,
    createdAt: '2023-11-15T12:45:00Z'
  },
  {
    application: 'Twitch',
    username: 'twitch@user',
    passphrase: '@senhatwitch',
    website: 'twitch.tv',
    notes: 'Some notes about Twitch.',
    userId: 1,
    tags: ['Gaming', 'Live Streaming'],
    favorite: true,
    inBin: false,
    createdAt: '2023-11-15T13:30:00Z'
  },
  {
    application: 'Airbnb',
    username: 'airbnb@user',
    passphrase: '@senhaairbnb',
    website: 'airbnb.com',
    notes: 'Some notes about Airbnb.',
    userId: 1,
    tags: ['Accommodation', 'vacation'],
    favorite: true,
    inBin: false,
    createdAt: '2023-11-15T09:00:00Z'
  },
  {
    application: 'Microsoft Teams',
    username: 'teams@user',
    passphrase: '@senhateams',
    website: 'teams.microsoft.com',
    notes: 'Some notes about Microsoft Teams.',
    userId: 1,
    tags: ['Business', 'Meetings'],
    favorite: false,
    inBin: false,
    createdAt: '2023-11-15T16:30:00Z'
  },
  {
    application: 'Pinterest',
    username: 'pinterest@user',
    passphrase: '@senhapinterest',
    website: 'pinterest.com',
    notes: 'Some notes about Pinterest.',
    userId: 1,
    tags: ['Social Media', 'Visual Discovery'],
    favorite: true,
    inBin: false,
    createdAt: '2023-11-15T16:00:00Z'
  },
  {
    application: 'Discord',
    username: 'discord@user',
    passphrase: '@senhadiscord',
    website: 'discord.com',
    notes: 'Some notes about Discord.',
    userId: 1,
    tags: ['Chat', 'Voice'],
    favorite: false,
    inBin: false,
    createdAt: '2023-11-15T15:45:00Z'
  },
  {
    application: 'teste1',
    username: '@tester',
    passphrase: '12345',
    website: 'teste.com.br',
    tags: ['teste', 'exemplo'],
    notes: 'senha criada para fins de teste.',
    userId: 1,
    favorite: false,
    inBin: false,
    createdAt: '2023-11-19T08:11:54.827Z'
  },
  {
    userId: 1,
    application: 'teste',
    favorite: false,
    username: 'teste',
    passphrase: 'teste',
    website: 'teste',
    tags: ['teste'],
    notes: '',
    inBin: false,
    createdAt: '2023-11-26T11:01:57.003Z'
  }
];
